server:
  port: 8081
dubbo:
  application:
    name: consumer
  registry:
    # please edit zookeeper address in your program.
    address: zookeeper://10.1.11.46:2181
  protocol:
    name: dubbo
    port: 8889